### PR TITLE
Add support for observability

### PR DESCRIPTION
**Pull request by acogoluegnes**
References #379

### CODE REVIEW

**Comment by acogoluegnes** [comment]
@marcingrzejszczak Feel free to have a look. Thanks!

**Comment by acogoluegnes** [comment]
[Documentation preview](https://rabbitmq.github.io/rabbitmq-stream-java-client/micrometer-observation/#micrometer-observation)

**Review by marcingrzejszczak — APPROVED** [review]
I went through the changes and they look great! Do you have a Zipkin screenshot from the tests?

**Comment by acogoluegnes** [comment]
@marcingrzejszczak Here you go:

image

Does that look good to you?

**Comment by marcingrzejszczak** [comment]
LGTM

**Pull request merged**
