### PR TITLE
Consumer flow strategy (take two)

### PR DESCRIPTION
**Pull request by acogoluegnes**
Rough draft.

### CODE REVIEW

**Comment by henry701** [comment]
I'll have a look at the code later, busy week here unfortunately, but regarding the comment, yeah, seems nice. Do we need chunk context being a type parameter? It makes sense for having a wide variety of strategies, but maybe we can just drop the idea since the implementation has been greatly simplified

**Comment by henry701** [comment]
Looks superb

**Comment by acogoluegnes** [comment]
> Do we need chunk context being a type parameter? It makes sense for having a wide variety of strategies, but maybe we can just drop the idea since the implementation has been greatly simplified. Then we don't need to cast in Client and nothing needs to use generics.

The chunk context is used only in the `ConsumersCoordinator`, so we should not hit a cast problem anywhere else in the library. I started to make `Client` generic and the genericity was more of a burden than a benefit as it needed to be `Void` everywhere but in `ConsumersCoordinator`. `Client` is not a public API, so I'd say it's fine.

Thanks for the review!

**Comment by acogoluegnes** [comment]
> Do we need chunk context being a type parameter? It makes sense for having a wide variety of strategies, but maybe we can just drop the idea since the implementation has been greatly simplified. Then we don't need to cast in Client and nothing needs to use generics.

Sorry for my comment above, I did not get your comment right. You are suggesting to make the "chunk context" the type we need for the consumer flow strategy, that is `ConsumerFlowStrategy.MessageProcessedCallback`, because we don't need it anywhere else. That's opinionated, but as it's just internal and it's not needed anywhere else, why not?

**Comment by henry701** [comment]
It worked like a charm in some local ad-hoc tests, never surpassing a certain threshold of messages (and certainly not two chunks at a time), inspecting the map of in-memory messages that I used here.
Also, the API and Javadoc are very clean and clear.
Nice!

**Comment by acogoluegnes** [comment]
Thanks @henry701 for testing this! Let's merge it.

**Pull request merged**
